import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ReactFlow, Handle, Position, Background, Controls, MarkerType } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import './style.css';
import './theme/react-flow.css';
import { analyze, parseProcess, sampleProcess } from './model.js';

const fmt = value => Number.isFinite(value) ? value.toLocaleString('en-US', { maximumFractionDigits: 1 }) : '—';
const field = value => Number.isNaN(value) ? '' : value;
const asNumber = event => event.target.value === '' ? NaN : Number(event.target.value);
const uid = prefix => `${prefix}-${crypto.randomUUID().slice(0, 8)}`;
function Step({ data }) {
  return <div className={`step ${data.kind}`}>
    {data.kind !== 'start' && <Handle type="target" position={Position.Left}/>}
    <span className="step-kind">{data.kind === 'review' ? data.teamName : data.kind === 'start' ? 'Start' : 'Complete'}</span>
    <strong>{data.label}</strong>
    {data.kind === 'review' && <div className="step-times"><span>{fmt(data.touch)}m touch</span><span>{fmt(data.wait)}m wait</span></div>}
    {data.kind === 'review' && <small>{data.requests == null ? 'Route needs repair' : `${fmt(data.requests)} requests/day`}</small>}
    {data.kind !== 'end' && <Handle type="source" position={Position.Right}/>}
  </div>;
}
const nodeTypes = { step: Step };
function App() {
  const [state, setState] = useState(() => { const p = sampleProcess(); return { draft: p, lastValid: p }; });
  const [baseline, setBaseline] = useState(sampleProcess);
  const [selected, setSelected] = useState('manager');
  const [measured, setMeasured] = useState({});
  const [route, setRoute] = useState('manager-procurement');
  const [notice, setNotice] = useState('Synthetic example loaded. Every change stays in this tab.');
  const [failed, setFailed] = useState(false);
  const revision = useRef(0);
  const p = state.draft;
  const result = useMemo(() => analyze(p), [p]);
  const reference = useMemo(() => analyze(baseline), [baseline]);
  const selectedNode = p.nodes.find(n => n.id === selected);
  const selectedRoute = p.edges.find(e => e.id === route);
  const update = next => { revision.current++; setState(current => { const draft = typeof next === 'function' ? next(current.draft) : next; return { draft, lastValid: analyze(draft).valid ? structuredClone(draft) : current.lastValid }; }); };
  const changeNode = (id, values) => update(current => ({ ...current, nodes: current.nodes.map(n => n.id === id ? { ...n, ...values } : n) }));
  const changeEdge = (id, values) => update(current => ({ ...current, edges: current.edges.map(e => e.id === id ? { ...e, ...values } : e) }));
  const deleteNode = id => update(current => ({ ...current, nodes: current.nodes.filter(n => n.id !== id), edges: current.edges.filter(e => e.source !== id && e.target !== id) }));
  function loadSample(simplified) { update(sampleProcess(simplified)); setBaseline(sampleProcess()); setSelected('manager'); setRoute('manager-procurement'); setFailed(false); setNotice(simplified ? '90/10 example loaded. Compare its routing against the original 70/30 policy.' : 'Original example restored, including the comparison baseline.'); }
  function download() { const url = URL.createObjectURL(new Blob([JSON.stringify(p, null, 2) + '\n'], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'approval-process.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  async function importFile(event) { const file = event.target.files[0]; if (!file) return; const requested = ++revision.current; try { if (file.size > 262144) throw Error('JSON limit is 256 KiB.'); const next = parseProcess(await file.text()); if (requested !== revision.current) return; update(next); setSelected(next.nodes.find(n => n.type === 'review')?.id || next.nodes[0].id); setRoute(next.edges[0]?.id || ''); setFailed(false); setNotice('Valid process imported. The comparison baseline is unchanged; use the baseline button to replace it.'); } catch (error) { if (requested !== revision.current) return; setFailed(true); setNotice(`${error.message} The previous process is unchanged.`); } finally { event.target.value = ''; } }
  function addStep() { const id = uid('step'); update(current => ({ ...current, nodes: [...current.nodes, { id, label: 'New review', type: 'review', team: current.teams[0].id, touch: 10, wait: 0, position: { x: 470, y: 350 } }] })); setSelected(id); }
  function addRoute(source, target) { const id = uid('route'); update(current => ({ ...current, edges: [...current.edges, { id, source, target, share: 100 }] })); setRoute(id); }
  const flowNodes = p.nodes.map(n => ({ id: n.id, type: 'step', position: n.position, measured: measured[n.id], deletable: n.type === 'review', selected: n.id === selected, data: { ...n, kind: n.type, teamName: p.teams.find(t => t.id === n.team)?.name || '', requests: result.valid ? result.rows.find(r => r.id === n.id)?.requests : null } }));
  const flowEdges = p.edges.map(e => ({ id: e.id, source: e.source, target: e.target, type: 'smoothstep', label: `${fmt(e.share)}%`, selected: e.id === route, markerEnd: { type: MarkerType.ArrowClosed, color: '#012169' }, labelStyle: { fontWeight: 700, fontSize: 12, fill: '#012169' }, labelBgStyle: { fill: '#FFFFFF', fillOpacity: 1 }, style: { strokeWidth: 2 } }));
  const saved = result.valid ? reference.elapsed - result.elapsed : null;
  const overloaded = result.valid ? result.teams.filter(t => t.load > 1) : [];
  return <>
    <a className="skip" href="#workspace">Skip to process editor</a>
    <header><a className="brand" href="#"><span className="brand-icon" aria-hidden="true">A</span><span>APPROVAL STUDIO<small>Process decisions, made visible</small></span></a><span className="local-badge">Local workspace</span><a href="https://github.com/jordanmeyer/bab-example-process">Source</a></header>
    <main>
      <section className="hero"><div><p className="eyebrow">A fictional purchase approval process</p><h1>Shorter routes.<br/>Same bottleneck?</h1><p>Change who reviews a request. Compare the time you enter with the work each team must absorb.</p></div><aside><span className="case-number">01</span><h2>The decision</h2><p>Send fewer requests through procurement. Does that reduce elapsed time—and does it fix the capacity problem?</p><button className="primary" onClick={() => loadSample(true)}>Try the 90/10 policy</button><button className="text-button" onClick={() => loadSample(false)}>Restore 70/30 example</button></aside></section>
      <div className={`notice ${failed ? 'error' : ''}`} role="status">{notice}</div>
      <section className="scenario-bar"><label>Scenario name<input value={p.name} maxLength="80" onChange={e => update({ ...p, name: e.target.value })}/></label><label className="arrivals">Requests per day<input type="number" min="0" max="10000" step="1" value={field(p.arrivals)} onChange={e => update({ ...p, arrivals: asNumber(e) })}/></label><div className="file-actions"><button disabled={!result.valid} onClick={download}>Export JSON</button><label className="file-button">Import JSON<input aria-label="Import process JSON" type="file" accept=".json,application/json" onChange={importFile}/></label></div></section>
      <section className="comparison" aria-live="polite"><article><p className="eyebrow">Expected elapsed / request</p><div className="big-number">{result.valid ? fmt(result.elapsed) : '—'}<span> min</span></div><p>{result.valid ? `${fmt(result.touch)} touch + ${fmt(result.wait)} entered wait` : 'Repair the routes to calculate this draft.'}</p></article><article><p className="eyebrow">Compared with baseline</p><div className={`big-number ${saved < 0 ? 'warning' : ''}`}>{saved == null ? '—' : `${saved > 0 ? '−' : saved < 0 ? '+' : ''}${fmt(Math.abs(saved))}`}<span> min</span></div><p>{saved == null ? 'No comparison while the draft is invalid.' : saved === 0 ? 'Same expected elapsed time as the baseline.' : !reference.elapsed ? 'Percentage change unavailable because the baseline time is zero.' : `${fmt(Math.abs(saved) / reference.elapsed * 100)}% ${saved > 0 ? 'less' : 'more'} entered elapsed time.`}</p></article><article><p className="eyebrow">Team capacity</p><div className={`big-number ${overloaded.length ? 'warning' : ''}`}>{result.valid ? overloaded.length : '—'}<span> over capacity</span></div><p>{result.valid ? overloaded.length ? `${overloaded.map(t => t.name).join(', ')} cannot keep up at these assumptions.` : 'Workload fits the entered productive capacity.' : 'No workload estimate for an invalid draft.'}</p></article></section>
      <div className="baseline"><p>Baseline: <strong>{baseline.name}</strong> · {fmt(reference.elapsed)} min/request · {fmt(baseline.arrivals)} requests/day</p><button className="text-button" disabled={!result.valid} onClick={() => { setBaseline(structuredClone(p)); setNotice('Current valid process is now the comparison baseline.'); setFailed(false); }}>Use current as baseline</button></div>
      <section id="workspace" className="editor"><div className="editor-heading"><div><p className="eyebrow">01 / Draw the route</p><h2>Every branch is a choice.</h2></div><button onClick={addStep} disabled={p.nodes.length >= 30}>Add review step</button></div><p className="instruction">Drag steps or connect their handles. Use the forms beside the diagram for every essential edit. Branches are alternatives, never parallel work.</p>
      {!result.valid && <div className="validation" role="alert"><strong>Draft needs repair. Results are paused.</strong><ul>{result.errors.map((error, i) => <li key={i}>{error}</li>)}</ul><button onClick={() => update(structuredClone(state.lastValid))}>Restore last valid process</button></div>}
      <div className="editor-grid"><div className="diagram" aria-label="Editable approval process"><ReactFlow nodes={flowNodes} edges={flowEdges} nodeTypes={nodeTypes} fitView minZoom={0.2} maxZoom={1.5} onNodeClick={(_, node) => setSelected(node.id)} onEdgeClick={(_, edge) => setRoute(edge.id)}
        onNodesChange={changes => {
          const sizes = changes.filter(c => c.type === 'dimensions' && c.dimensions);
          if (sizes.length) setMeasured(current => ({ ...current, ...Object.fromEntries(sizes.map(c => [c.id, c.dimensions])) }));
          const selection = changes.find(c => c.type === 'select' && c.selected);
          if (selection) setSelected(selection.id);
          if (!changes.some(c => c.type === 'position' || c.type === 'remove')) return;
          update(current => { const removed = new Set(changes.filter(c => c.type === 'remove' && current.nodes.find(n => n.id === c.id)?.type === 'review').map(c => c.id)); return { ...current, nodes: current.nodes.filter(n => !removed.has(n.id)).map(n => { const move = changes.find(c => c.id === n.id && c.type === 'position' && c.position); return move ? { ...n, position: move.position } : n; }), edges: current.edges.filter(e => !removed.has(e.source) && !removed.has(e.target)) }; }); }}
        onEdgesChange={changes => { const removed = new Set(changes.filter(c => c.type === 'remove').map(c => c.id)); if (removed.size) update(current => ({ ...current, edges: current.edges.filter(e => !removed.has(e.id)) })); }}
        onConnect={({ source, target }) => addRoute(source, target)} onReconnect={(old, connection) => changeEdge(old.id, { source: connection.source, target: connection.target })}>
        <Background color="#E2E6ED" gap={24}/><Controls showInteractive={false}/></ReactFlow></div>
        <aside className="inspector"><h3>Edit without dragging</h3><label>Review step<select value={selectedNode?.id || ''} onChange={e => setSelected(e.target.value)}>{!selectedNode && <option value="">Choose a step</option>}{p.nodes.map(n => <option key={n.id} value={n.id}>{n.label}</option>)}</select></label>{selectedNode && <><label>Step label<input value={selectedNode.label} maxLength="80" onChange={e => changeNode(selectedNode.id, { label: e.target.value })}/></label>{selectedNode.type === 'review' && <><label>Responsible team<select value={selectedNode.team} onChange={e => changeNode(selectedNode.id, { team: e.target.value })}>{p.teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="two-fields"><label>Touch time · min<input type="number" min="0" max="4800" value={field(selectedNode.touch)} onChange={e => changeNode(selectedNode.id, { touch: asNumber(e) })}/></label><label>Entered wait · min<input type="number" min="0" max="43200" value={field(selectedNode.wait)} onChange={e => changeNode(selectedNode.id, { wait: asNumber(e) })}/></label></div><button className="text-button danger" onClick={() => deleteNode(selectedNode.id)}>Delete this review step</button></>}</>}
        <hr/><label>Route<select value={selectedRoute?.id || ''} onChange={e => setRoute(e.target.value)}>{!selectedRoute && <option value="">Choose a route</option>}{p.edges.map(e => <option key={e.id} value={e.id}>{p.nodes.find(n => n.id === e.source)?.label} to {p.nodes.find(n => n.id === e.target)?.label}</option>)}</select></label>{selectedRoute && <><div className="two-fields"><label>From<select value={selectedRoute.source} onChange={e => changeEdge(selectedRoute.id, { source: e.target.value })}>{p.nodes.map(n => <option value={n.id} key={n.id}>{n.label}</option>)}</select></label><label>To<select value={selectedRoute.target} onChange={e => changeEdge(selectedRoute.id, { target: e.target.value })}>{p.nodes.map(n => <option value={n.id} key={n.id}>{n.label}</option>)}</select></label></div><label>Share taking this route · %<input type="number" min="0" max="100" step="any" value={field(selectedRoute.share)} onChange={e => changeEdge(selectedRoute.id, { share: asNumber(e) })}/></label><button className="text-button danger" onClick={() => update({ ...p, edges: p.edges.filter(e => e.id !== selectedRoute.id) })}>Delete this route</button></>}
        <button className="add-route" disabled={p.edges.length >= 60} onClick={() => addRoute(selectedNode?.id || p.nodes[0].id, p.nodes.find(n => n.type === 'end').id)}>Add route from selected step</button></aside></div></section>
      <section className="capacity-section"><div><p className="eyebrow">02 / Check the workload</p><h2>Faster routing is not more capacity.</h2><p>Minutes of productive work needed per day, compared with minutes available. Entered waiting times do not consume team capacity.</p></div><div className="team-grid">{p.teams.map(team => { const calculated = result.valid ? result.teams.find(t => t.id === team.id) : null; return <article className="team" key={team.id}><h3>{team.name}</h3><p className="team-load">{calculated ? fmt(calculated.load * 100) : '—'}<span>% loaded</span></p><div className="load-track" aria-hidden="true"><i style={{ width: `${Math.min(100, calculated?.load * 100 || 0)}%`, background: calculated?.load > 1 ? 'var(--duke-copper)' : 'var(--duke-navy-blue)' }}/></div><p>{calculated ? `${fmt(calculated.work)} min of work / day${calculated.excess ? ` · ${fmt(calculated.excess)} min over capacity` : ''}` : 'Repair draft to calculate workload.'}</p><label>{team.name} capacity · productive min/day<input type="number" min="1" max="100000" value={field(team.capacity)} onChange={e => update({ ...p, teams: p.teams.map(t => t.id === team.id ? { ...t, capacity: asNumber(e) } : t) })}/></label></article>; })}</div><p className="capacity-note">A load above 100% means demand exceeds the entered capacity. At 100%, there is no spare capacity. This model does not predict queue length, waiting time or a stable backlog.</p></section>
      <section className="audit"><p className="eyebrow">03 / Follow the calculation</p><h2>Weighted paths, visible assumptions.</h2><div className="table-wrap" tabIndex="0" role="region" aria-label="Step calculations"><table><caption>Current draft · per request and per day</caption><thead><tr><th>Step</th><th>Share visiting</th><th>Requests/day</th><th>Touch min/request</th><th>Wait min/request</th></tr></thead><tbody>{result.valid ? result.rows.map(n => <tr key={n.id}><td>{n.label}</td><td>{fmt(n.visits * 100)}%</td><td>{fmt(n.requests)}</td><td>{fmt(n.expectedTouch)}</td><td>{fmt(n.expectedWait)}</td></tr>) : <tr><td colSpan="5">Repair draft routes to see the calculations.</td></tr>}</tbody></table></div><details><summary>Model and JSON contract</summary><div className="method"><p>Starting visit probability is 100%. Each outgoing route receives its source probability × its entered share. Probabilities add at merges. Expected touch and wait are sums of each step’s time × its visit probability. Team work/day = requests/day × expected touch at that team. Capacity load = work/day ÷ productive minutes/day.</p><p>Only mutually exclusive routes, one start, one completion, and no loops. Every step must be connected from start to completion. Each non-completion step’s outgoing shares must sum to 100% (floating-point tolerance 0.00000001 percentage points); errors are never normalized. Zero-share routes are permitted. Entered times describe sequential tasks; there is no parallel work, rework, calendar, cost, queueing or stochastic simulation. With zero arrivals, conditional time per request is still shown and daily work is zero. Averages do not describe every request.</p><p>Export a valid example to inspect version 1 JSON. Required top-level fields: version, name, arrivals, teams, nodes, edges. A team has id/name/capacity. A node has id/label/type/team/touch/wait/position (x/y). A route has id/source/target/share. Exact fields only. Up to 8 teams, 30 steps, 60 routes and 256 KiB. Names/labels: 1–80 characters. IDs: a letter followed by letters, digits, underscores or hyphens, at most 40 characters. Positions: ±5,000. Arrivals: 0–10,000/day; touch: 0–4,800 min; wait: 0–43,200 min; capacity: 1–100,000 productive min/day. Start/end have null team and zero times.</p><p>Imported JSON is validated before replacement. No files or scenarios are uploaded or stored. Refresh restores the original example; export your valid process to keep it. The comparison baseline is a separate in-memory snapshot. Both examples are invented and are not evidence of actual business performance.</p></div></details></section>
      <footer><p>Independent classroom example. No institutional affiliation or endorsement.</p><a href="https://github.com/jordanmeyer/bab-example-process">View source</a><a href="./THIRD-PARTY-NOTICES.txt">Library notices</a></footer>
    </main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
