import { analyze, validate, parseProcess, sampleProcess } from '../app/model.js';
let count=0, failures=0;
const near=(actual,expected)=>{if(!Number.isFinite(actual)||Math.abs(actual-expected)>1e-9) throw Error(`expected ${expected}; observed ${actual}`);};
const equal=(actual,expected)=>{if(JSON.stringify(actual)!==JSON.stringify(expected)) throw Error(`expected ${JSON.stringify(expected)}; observed ${JSON.stringify(actual)}`);};
function check(name,fn){count++;const li=document.createElement('li');try{fn();li.textContent=`PASS — ${name}`;li.className='pass';}catch(e){failures++;li.textContent=`FAIL — ${name}: ${e.message}`;li.className='fail';}document.getElementById('results').append(li);}
function invalid(name,change,match){check(name,()=>{const p=sampleProcess();change(p);const r=analyze(p);if(r.valid||!r.errors.join(' ').includes(match))throw Error(`expected ${match}; observed ${JSON.stringify(r)}`);});}
const base=analyze(sampleProcess()), simple=analyze(sampleProcess(true));
check('Baseline: 8 + .3×25 + 12 = 27.5 touch minutes',()=>near(base.touch,27.5));
check('Baseline entered wait: 120 + .3×480 + 180 = 444 minutes',()=>near(base.wait,444));
check('Baseline elapsed: 27.5 + 444 = 471.5 minutes',()=>near(base.elapsed,471.5));
check('90/10 elapsed: 8 + .1×25 + 12 + 120 + .1×480 + 180 = 370.5',()=>near(simple.elapsed,370.5));
check('Changing routing saves 101 minutes and finance work stays 480/day',()=>{near(base.elapsed-simple.elapsed,101);near(simple.teams.find(t=>t.id==='finance').work,480);});
check('Finance 480/420 is 8/7 loaded and 60 minutes over capacity',()=>{const t=base.teams.find(t=>t.id==='finance');near(t.load,8/7);near(t.excess,60);});
check('Procurement demand falls from 300 to 100 productive minutes/day',()=>{near(base.teams.find(t=>t.id==='procurement').work,300);near(simple.teams.find(t=>t.id==='procurement').work,100);});
check('Merged finance receives all 40 requests, not 28 + 40',()=>near(base.rows.find(n=>n.id==='finance').requests,40));
check('Zero arrivals means zero daily work; per-request path time still 471.5',()=>{const p=sampleProcess();p.arrivals=0;const r=analyze(p);near(r.elapsed,471.5);equal(r.teams.map(t=>t.work),[0,0,0]);});
check('Doubling arrivals doubles work and preserves elapsed assumptions',()=>{const p=sampleProcess();p.arrivals=80;const r=analyze(p);near(r.elapsed,471.5);near(r.teams[2].work,960);});
check('Changing capacity does not change entered elapsed time',()=>{const p=sampleProcess();p.teams[2].capacity=480;const r=analyze(p);near(r.elapsed,471.5);near(r.teams[2].load,1);near(r.teams[2].excess,0);});
check('Zero-share procurement is valid, contributes no visits or time',()=>{const p=sampleProcess(true);p.edges[1].share=0;p.edges[2].share=100;const r=analyze(p);near(r.elapsed,320);near(r.rows.find(n=>n.id==='procurement').visits,0);});
check('100% procurement yields 8+25+12+120+480+180 = 825 minutes',()=>{const p=sampleProcess();p.edges[1].share=100;p.edges[2].share=0;near(analyze(p).elapsed,825);});
check('Input and node coordinates remain unmodified by analysis',()=>{const p=sampleProcess();const before=JSON.stringify(p);analyze(p);equal(JSON.stringify(p),before);});
check('JSON export/import round trip preserves a valid exact process',()=>equal(parseProcess(JSON.stringify(sampleProcess())),sampleProcess()));
invalid('Wrong branch sum reports the responsible step and exact 95%',p=>p.edges[1].share=25,'Manager approval: outgoing shares total 95%');
invalid('Fractional routing is not silently normalized',p=>p.edges[1].share=29.999,'99.999%');
invalid('A true cycle is rejected before calculating',p=>{p.edges[3].share=90;p.edges.push({id:'cycle',source:'procurement',target:'manager',share:10});},'loop');
invalid('Disconnected review is rejected',p=>p.nodes.push({...p.nodes[1],id:'orphan',label:'Orphan'}),'Orphan:');
invalid('Duplicate node ID is rejected',p=>p.nodes[2].id='manager','unique IDs');
invalid('Unknown team is rejected',p=>p.nodes[1].team='missing','existing team');
invalid('Zero capacity is rejected instead of dividing by zero',p=>p.teams[0].capacity=0,'capacity');
invalid('Negative touch time is rejected',p=>p.nodes[1].touch=-1,'touch');
invalid('Nonfinite wait time is rejected',p=>p.nodes[1].wait=Infinity,'wait');
invalid('Self-connection is rejected',p=>p.edges[0].target='start','two different');
invalid('Duplicate route pair is rejected',p=>p.edges.push({...p.edges[0],id:'duplicate'}),'unique IDs/pairs');
invalid('Unknown route endpoint is rejected',p=>p.edges[0].target='missing','existing steps');
invalid('Multiple starts are rejected',p=>{p.nodes[2].type='start';p.nodes[2].team=null;p.nodes[2].touch=0;p.nodes[2].wait=0;},'exactly one');
invalid('Completion cannot contain ignored work',p=>p.nodes[4].touch=5,'cannot carry work');
check('Malformed JSON rejects with useful wording',()=>{let error;try{parseProcess('{oops');}catch(e){error=e;}if(!error?.message.includes('valid JSON'))throw Error('missing format error');});
check('Null row is rejected with a schema error, not a crash',()=>{const p=sampleProcess();p.nodes[1]=null;const errors=validate(p);if(!errors[0].includes('Each step'))throw Error(errors.join(' '));});
check('Unrecognized fields are rejected',()=>{const p=sampleProcess();p.secret='discard me';if(!validate(p).length)throw Error('extra field accepted');});
check('JSON byte limit is checked before parsing',()=>{let error;try{parseProcess('x'.repeat(262145));}catch(e){error=e;}if(!error?.message.includes('256 KiB'))throw Error('missing size error');});
check('HTML-looking labels remain plain strings in the model',()=>{const p=sampleProcess();p.nodes[1].label='<b>Manager</b>';equal(parseProcess(JSON.stringify(p)).nodes[1].label,'<b>Manager</b>');});
check('Numerical assertions reject NaN, undefined and infinity',()=>{for(const value of [NaN,undefined,Infinity]){let rejected=false;try{near(value,1);}catch{rejected=true;}if(!rejected)throw Error('nonfinite value passed');}});
const merge = parseProcess(await (await fetch('./fixtures/reviewer-merge.json')).text());
check('Independent multi-merge: C40%, D60%, 175 touch +18 wait =193',()=>{const r=analyze(merge);near(r.rows.find(n=>n.id==='c').visits,.4);near(r.rows.find(n=>n.id==='d').visits,.6);near(r.touch,175);near(r.wait,18);near(r.elapsed,193);near(r.teams[0].work,1750);});
const large = parseProcess(await (await fetch('./fixtures/reviewer-long.json')).text());
check('Supported large bound: 9,600 minutes and 96,000,000 work/day',()=>{const r=analyze(large);near(r.elapsed,9600);near(r.teams[0].work,96000000);near(r.teams[0].load*100,9600000000);});
const status=document.getElementById('status');status.textContent=`${count-failures}/${count} passed; ${failures} failed.`;status.className=failures?'fail':'pass';
