import {day,iso,schedule,parsePlan,samplePlan,chartTasks} from '../app/model.js';
let count=0,failures=0;
const equal=(actual,expected)=>{if(JSON.stringify(actual)!==JSON.stringify(expected))throw Error(`Expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);};
function check(name,fn){count++;const li=document.createElement('li');try{fn();li.textContent='PASS — '+name;li.className='pass';}catch(e){failures++;li.textContent='FAIL — '+name+': '+e.message;li.className='fail';}document.getElementById('results').append(li);}
const valid=p=>{const r=schedule(p);if(!r.valid)throw Error(r.errors.join(' '));return r;};
const reject=(name,mutate,fragment)=>check(name,()=>{const p=samplePlan();mutate(p);const r=schedule(p);equal(r.valid,false);if(!r.errors.join(' ').includes(fragment))throw Error(r.errors.join(' '));});
const mini=(start='2026-01-05')=>({version:1,name:'Two tasks',start,promise:'2026-01-20',tasks:[{id:'a',name:'A',duration:2,release:null,dependencies:[]},{id:'b',name:'B',duration:3,release:null,dependencies:['a']}]});
check('Manual critical path 5+10+4+7+1=27, November2→29',()=>{const r=valid(samplePlan());equal(r.span,27);equal(iso(r.finish),'2026-11-29');equal(r.buffer,2);});
check('Manual row boundaries for all seven original workstreams',()=>equal(valid(samplePlan()).rows.map(t=>[t.id,iso(t.start),iso(t.end)]),[['validation','2026-11-02','2026-11-07'],['packaging','2026-11-07','2026-11-15'],['supplier','2026-11-07','2026-11-17'],['pilot','2026-11-17','2026-11-21'],['safety','2026-11-21','2026-11-28'],['sales','2026-11-15','2026-11-21'],['launch','2026-11-28','2026-11-29']]));
check('Packaging2days and sales7days float; five zero-float tasks',()=>equal(valid(samplePlan()).rows.map(t=>t.float),[0,2,0,0,0,7,0]));
for(const preset of ['packaging','safety'])check(`${preset} delay: 30days, December2,1day late`,()=>{const r=valid(samplePlan(preset));equal([r.span,iso(r.finish),r.buffer],[30,'2026-12-02',-1]);});
check('Packaging+2 consumes float without moving ready date',()=>{const p=samplePlan();p.tasks[1].duration+=2;const r=valid(p);equal(iso(r.finish),'2026-11-29');equal(r.rows[1].float,0);equal(r.rows[2].float,0);});
check('Changing promise never changes dates or total float',()=>{const p=samplePlan();const before=valid(p);p.promise='2026-11-01';const after=valid(p);equal(after.rows,before.rows);equal(after.buffer,-28);});
check('End-exclusive: A Jan5→7, B startsJan7 and endsJan10',()=>equal(valid(mini()).rows.map(t=>[iso(t.start),iso(t.end)]),[['2026-01-05','2026-01-07'],['2026-01-07','2026-01-10']]));
check('Leap-year February28+2=March1 in2024',()=>equal(iso(day('2024-02-28')+2),'2024-03-01'));
check('Non-leap February28+2=March2 in2026',()=>equal(iso(day('2026-02-28')+2),'2026-03-02'));
check('Year boundary December31+2=January2',()=>equal(iso(day('2026-12-31')+2),'2027-01-02'));
check('DST weekends do not change whole-day durations',()=>{equal(iso(day('2026-03-07')+2),'2026-03-09');equal(iso(day('2026-10-31')+2),'2026-11-02');});
check('Reordered input resolves dependencies before dates',()=>{const p=mini();p.tasks.reverse();equal(iso(valid(p).finish),'2026-01-10');equal(valid(p).rows[0].id,'b');});
check('Release gap controls B; A gains3days float',()=>{const p=mini();p.tasks[1].release='2026-01-10';const r=valid(p);equal(r.rows.map(t=>[iso(t.start),t.float]),[['2026-01-05',3],['2026-01-10',0]]);equal(iso(r.finish),'2026-01-13');});
check('Release before project start cannot schedule earlier',()=>{const p=mini();p.tasks[0].release='2025-12-01';equal(iso(valid(p).rows[0].start),'2026-01-05');});
check('Multiple terminal tasks use overall completion',()=>{const p=mini();p.tasks[1].dependencies=[];const r=valid(p);equal(iso(r.finish),'2026-01-08');equal(r.rows.map(t=>t.float),[1,0]);});
check('Pure calculation never mutates input',()=>{const p=samplePlan();const before=JSON.stringify(p);schedule(p);equal(JSON.stringify(p),before);});
check('Exact JSON round trip',()=>equal(parsePlan(JSON.stringify(samplePlan())),samplePlan()));
check('Safe ordinal adapter handles HTML names and prototype-like IDs',()=>{const p=mini();p.tasks[0].id='constructor';p.tasks[0].name='<img src=x onerror=alert(1)>';p.tasks[1].dependencies=['constructor'];const rows=chartTasks(valid(p).rows);equal(rows.map(t=>[t.id,t.name,t.dependencies]),[['task1','01 · 2d',[]],['task2','02 · 3d',['task1']]]);});
check('Frappe adapter gives inclusive lastoccupied days Jan6/Jan9',()=>equal(chartTasks(valid(mini()).rows).map(t=>[t.start,t.end]),[['2026-01-05','2026-01-06'],['2026-01-07','2026-01-09']]));
check('Single-day chart task has matching start and inclusiveend',()=>{const p=mini();p.tasks[0].duration=1;const t=chartTasks(valid(p).rows)[0];equal(t.start,t.end);});
reject('Cycle rejected',p=>p.tasks[0].dependencies=['launch'],'cycle');
reject('Missing dependency rejected',p=>p.tasks[0].dependencies=['missing'],'does not exist');
reject('Self dependency rejected',p=>p.tasks[0].dependencies=['validation'],'itself');
reject('Duplicate dependency rejected',p=>p.tasks[1].dependencies=['validation','validation'],'unique task IDs');
reject('Duplicate task ID rejected',p=>p.tasks[1].id='validation','unique');
reject('Non-whole duration rejected',p=>p.tasks[0].duration=1.5,'whole number');
reject('Zero duration rejected',p=>p.tasks[0].duration=0,'whole number');
reject('Nonfinite duration rejected',p=>p.tasks[0].duration=NaN,'whole number');
reject('Impossible calendar date rejected',p=>p.start='2026-02-30','real dates');
reject('Bad release date rejected',p=>p.tasks[0].release='2026-02-29','earliest permitted');
reject('Extra field rejected',p=>p.owner='someone','version 1');
reject('Null task rejected usefully',p=>p.tasks[0]=null,'Each task');
reject('Excessive schedule horizon rejected',p=>p.tasks[0].release='2030-01-01','730');
reject('Empty schedule rejected',p=>p.tasks=[],'1–30');
reject('Overlong name rejected',p=>p.tasks[0].name='W'.repeat(81),'1–80');
check('Malformed JSON rejected',()=>{let error;try{parsePlan('{oops');}catch(e){error=e;}equal(error?.message,'This file is not valid JSON.');});
check('Byte limit catches multibyte input',()=>{let error;try{parsePlan('é'.repeat(65537));}catch(e){error=e;}equal(error?.message,'Use a JSON file no larger than 128 KiB.');});
const dst=parsePlan(await (await fetch('./fixtures/reviewer-dst.json')).text());
check('Independent scrambled DST release/merge:9days,−1buffer,onlyEcritical',()=>{const r=valid(dst);equal([r.span,r.buffer,iso(r.finish)],[9,-1,'2026-03-15']);equal(r.rows.map(t=>[iso(t.start),iso(t.end),t.float]),[['2026-03-10','2026-03-11',2],['2026-03-06','2026-03-08',2],['2026-03-14','2026-03-15',0],['2026-03-11','2026-03-13',2],['2026-03-08','2026-03-11',2]]);});
const boundary=parsePlan(await (await fetch('./fixtures/reviewer-boundary.json')).text());
check('Independent maximum:365+365=730days toDec31,2025; oneextra rejected',()=>{const r=valid(boundary);equal([r.span,r.buffer,iso(r.finish)],[730,0,'2025-12-31']);const p=structuredClone(boundary);p.tasks.push({id:'extra',name:'Extra',duration:1,release:null,dependencies:[p.tasks[1].id]});equal(schedule(p).valid,false);});
const status=document.getElementById('status');status.textContent=`${count-failures}/${count} passed; ${failures} failed.`;status.className=failures?'fail':'pass';
