import { parseSales, filterSales, totals } from '../app/model.js';
import example from '../app/example.csv?raw';
import { checkChart } from './chart.js';
const header = 'region,product,quantity,unit_price,unit_cost\n';
const cases = [];
const equal = (actual, expected) => { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw Error(`Expected ${JSON.stringify(expected)}; observed ${JSON.stringify(actual)}`); };
const test = (name, run) => cases.push([name, run]);
const rejects = (text, fragment) => { try { parseSales(text); } catch (error) { if (!error.message.includes(fragment)) throw error; return; } throw Error('Invalid input was accepted'); };
// Expected answers come from the agreed hand derivation in PLAN.md, not app output.
test('Example: revenue 39000, cost 23400, contribution 15600 cents', () => equal(totals(parseSales(example)), { revenue:39000,cost:23400,profit:15600 }));
test('North intersection: 24000/14400/9600 cents', () => equal(totals(filterSales(parseSales(example), 'North','Notebook')), {revenue:24000,cost:14400,profit:9600}));
test('South: 15000/9000/6000 cents', () => equal(totals(filterSales(parseSales(example), 'South')), {revenue:15000,cost:9000,profit:6000}));
test('Empty North/Pen intersection: zeros', () => equal(totals(filterSales(parseSales(example), 'North','Pen')), {revenue:0,cost:0,profit:0}));
test('Zero quantity and a loss: 3×0.10 minus 3×0.20 = −30 cents', () => equal(totals(parseSales(header+'N,X,0,8,3\nN,Y,3,0.10,0.20')), {revenue:30,cost:60,profit:-30}));
test('BOM, CRLF, quoted commas, escaped quotes and literal HTML', () => { const row=parseSales('\uFEFF'+header.replace('\n','\r\n')+'"North, east","<img src=x onerror=alert(1)> ""pen""",2,1.05,0.01\r\n')[0];equal([row.region,row.product,row.revenue,row.cost],['North, east','<img src=x onerror=alert(1)> "pen"',210,2]); });
test('Reordered exact headers', () => equal(parseSales('product,quantity,unit_cost,region,unit_price\nPen,1,1,N,2')[0].profit,100));
test('Unclosed quote rejected', () => rejects(header+'N,"bad,1,2,1','Invalid CSV'));
test('Extra field rejected', () => rejects(header+'N,P,1,2,1,extra','five fields'));
test('Missing field rejected', () => rejects(header+'N,P,1,2','five fields'));
test('Missing header rejected', () => rejects('region,product,quantity,unit_price\nN,P,1,2','headers'));
test('Duplicate header rejected', () => rejects('region,product,quantity,unit_price,unit_price\nN,P,1,2,3','headers'));
test('Extra precision rejected, not rounded', () => rejects(header+'N,P,1,1.001,0','two decimals'));
test('Blank price rejected', () => rejects(header+'N,P,1,,0','two decimals'));
test('Negative price rejected', () => rejects(header+'N,P,1,-1,0','two decimals'));
test('Fractional units rejected', () => rejects(header+'N,P,1.5,2,0','whole number'));
test('Exponent notation rejected', () => rejects(header+'N,P,1,1e2,0','two decimals'));
test('Empty dataset rejected', () => rejects(header,'1–5,000'));
test('Blank region rejected', () => rejects(header+',P,1,2,1','region'));
test('Labels longer than 120 rejected', () => rejects(header+'N,'+'P'.repeat(121)+',1,2,1','product'));
test('Input maxima accepted exactly', () => equal(parseSales(header+'N,P,1000000,1000000,1000000')[0].revenue,100000000000000));
test('Quantity limit enforced', () => rejects(header+'N,P,1000001,1,1','whole number'));
test('Price limit enforced', () => rejects(header+'N,P,1,1000000.01,1','two decimals'));
test('5,000 rows: each 2×$1.05/$0.20, total $10,500/$2,000/$8,500', () => equal(totals(parseSales(header+('N,P,2,1.05,0.20\n').repeat(5000))),{revenue:1050000,cost:200000,profit:850000}));
test('5,001 rows rejected', () => rejects(header+('N,P,1,1,0\n').repeat(5001),'1–5,000'));
test('2 MB UTF-8 size limit enforced', () => rejects(header+'é'.repeat(1000000),'2 MB'));
test('Unsafe aggregate cents rejected', () => rejects(header+('N,P,1000000,1000000,0\n').repeat(100),'exact-cent'));
test('Chart hidden-to-visible resize; solid normal/highlight/blur/select fills; disposal', checkChart);
let passed=0;
for (const [name, run] of cases) { const li=document.createElement('li'); try { await run(); passed++;li.textContent=`PASS — ${name}`; } catch(error) { li.textContent=`FAIL — ${name}: ${error.message}`; } document.querySelector('#results').append(li); }
document.querySelector('#summary').textContent=`${passed}/${cases.length} passed; ${cases.length-passed} failed.`;
