import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MantineProvider,Button,NativeSelect,NumberInput,TextInput,Modal,SegmentedControl} from '@mantine/core';
import * as echarts from 'echarts/core';
import {LineChart,BarChart} from 'echarts/charts';
import {GridComponent,TooltipComponent,MarkLineComponent,AriaComponent} from 'echarts/components';
import {SVGRenderer} from 'echarts/renderers';
echarts.use([LineChart,BarChart,GridComponent,TooltipComponent,MarkLineComponent,AriaComponent,SVGRenderer]);
import {TabulatorFull} from 'tabulator-tables';
import '@mantine/core/styles.css';
import 'tabulator-tables/dist/css/tabulator.min.css';
import './theme/duke-tokens.css';
import './theme/base.css';
import './theme/mantine.css';
import './theme/tabulator.css';
import './style.css';
import {mantineTheme} from './theme/mantine.js';
import {echartsTheme} from './theme/echarts.js';
import {duke} from './theme/tokens.js';
import {records,stores,months,monthLabels} from './data.js';
import {summarize,selectRows,status,costBridge,money,exactMoney,percent,signedPercent,points} from './model.js';

function Chart({option,label,onClick}) {
 const host=useRef();
 useEffect(()=>{
  const chart=echarts.init(host.current,echartsTheme(),{renderer:'svg'});
  chart.setOption({...option,animation:false,aria:{enabled:true,label:{description:label}},tooltip:{trigger:'axis',renderMode:'richText'}});
  if(onClick) chart.on('click',onClick);
  const resize=new ResizeObserver(()=>chart.resize());resize.observe(host.current);
  return ()=>{resize.disconnect();chart.dispose();};
 },[option]);
 return <div ref={host} className="chart" role="img" aria-label={label}/>;
}

const columnLabels={sales:'Sales',product:'Product cost',labor:'Store labor',other:'Occupancy / other'};
function Ledger({rows,onInspect,sort}) {
 const host=useRef();const table=useRef();const ready=useRef(false);const latest=useRef(rows);latest.current=rows;
 useEffect(()=>{
  const value=new TabulatorFull(host.current,{data:latest.current.map(row=>({...row,...summarize([row])})),layout:'fitDataStretch',height:385,placeholder:'No records match these filters.',columns:[
   {title:'Store',field:'store',width:170,formatter:cell=>{const button=document.createElement('button');button.textContent=cell.getValue();button.className='table-store';button.addEventListener('click',()=>onInspect(cell.getRow().getData().storeId,cell.getRow().getData().month));return button;}},
   {title:'Month',field:'month',width:105,formatter:'plaintext'}, {title:'Region',field:'region',width:115,formatter:'plaintext'},
   ...['sales','contribution'].map(key=>({title:key==='sales'?'Sales, USD':'Contribution, USD',field:key,width:145,sorter:'number',hozAlign:'right',formatter:cell=>exactMoney(cell.getValue())})),
   {title:'Margin',field:'margin',width:100,sorter:'number',hozAlign:'right',formatter:cell=>percent(cell.getValue())},
   {title:'Sales YoY',field:'growth',width:105,sorter:'number',hozAlign:'right',formatter:cell=>signedPercent(cell.getValue())},
   ...['product','labor','other'].map(key=>({title:columnLabels[key]+', USD',field:key,width:key==='other'?190:155,sorter:'number',hozAlign:'right',formatter:cell=>exactMoney(cell.getValue())})),
   {title:'Transactions',field:'transactions',width:125,sorter:'number',hozAlign:'right'}, {title:'Labor hours',field:'hours',width:125,sorter:'number',hozAlign:'right'},
   {title:'Sales / labor hr',field:'salesPerHour',width:150,sorter:'number',hozAlign:'right',formatter:cell=>exactMoney(cell.getValue())},
   {title:'Avg. ticket',field:'ticket',width:120,sorter:'number',hozAlign:'right',formatter:cell=>exactMoney(cell.getValue())}
  ]});
  table.current=value;value.on('tableBuilt',()=>{ready.current=true;value.replaceData(latest.current.map(row=>({...row,...summarize([row])})));value.setSort('margin','asc');});
  return ()=>{ready.current=false;value.destroy();};
 },[]);
 useEffect(()=>{if(ready.current)table.current.replaceData(rows.map(row=>({...row,...summarize([row])})));},[rows]);
 useEffect(()=>{if(ready.current)table.current.setSort(sort,'asc');},[sort]);
 return <div className="ledger-scroll" tabIndex="0" aria-label="Scrollable operating ledger"><div ref={host} className="bab-table"/></div>;
}
function Detail({detail,onClose,onReturnFocus}) {
 if(!detail)return <Modal opened={false} onClose={onClose} returnFocus={false} onExitTransitionEnd={onReturnFocus} closeButtonProps={{'aria-label':'Close store details'}}/>;
 const row=records.find(row=>row.storeId===detail.id&&row.month===detail.month);
 const store=stores.find(store=>store.id===detail.id);const index=months.indexOf(detail.month);
 const previous=index?records.find(r=>r.storeId===detail.id&&r.month===months[index-1]):null;
 const current=summarize([row]);const prior=previous?summarize([previous]):null;
 return <Modal opened onClose={onClose} returnFocus={false} onExitTransitionEnd={onReturnFocus} closeButtonProps={{'aria-label':'Close store details'}} title={`${store.name} · ${monthLabels[index]} 2026`} size="xl" centered>
  <p className="eyebrow">STORE {store.id} · {store.region.toUpperCase()} · SYNTHETIC DATA</p>
  <div className="detail-metrics"><div><span>Store contribution</span><strong>{money(current.contribution)}</strong></div><div><span>Contribution margin</span><strong>{percent(current.margin)}</strong></div><div><span>Sales per labor hour</span><strong>{exactMoney(current.salesPerHour)}</strong></div></div>
  <h3>Follow the change in the ledger</h3>
  {previous?<><p>Compared with {monthLabels[index-1]}: contribution {current.contribution>=prior.contribution?'rose':'fell'} by {exactMoney(Math.abs(current.contribution-prior.contribution))}; margin moved {points(current.margin-prior.margin)}. Rates use each month's own sales.</p>
  <div className="native-scroll"><table><caption>Cost bridge · exact USD and percentage-point changes</caption><thead><tr><th>Line</th><th>{monthLabels[index-1]}</th><th>{monthLabels[index]}</th><th>Change, USD</th><th>Share of sales change</th></tr></thead><tbody>{costBridge(row,previous).map(item=><tr key={item.key}><th>{columnLabels[item.key]}</th><td>{exactMoney(item.previous)}</td><td>{exactMoney(item.current)}</td><td>{item.change>=0?'+':''}{exactMoney(item.change)}</td><td>{item.key==='sales'?'—':points(item.ratioChange)}</td></tr>)}<tr className="total"><th>Contribution</th><td>{exactMoney(prior.contribution)}</td><td>{exactMoney(current.contribution)}</td><td>{exactMoney(current.contribution-prior.contribution)}</td><td>{points(current.margin-prior.margin)}</td></tr></tbody></table></div>
  <p className="detail-note">Labor hours: {previous.hours.toLocaleString()} to {row.hours.toLocaleString()}. Transactions: {previous.transactions.toLocaleString()} to {row.transactions.toLocaleString()}. Sales per labor hour: {exactMoney(prior.salesPerHour)} to {exactMoney(current.salesPerHour)}.</p></>:<p>April is the first month in the sample; no preceding month is available. April sales are {exactMoney(row.sales)}, product cost {exactMoney(row.product)}, labor {exactMoney(row.labor)}, occupancy/other {exactMoney(row.other)}.</p>}
  <div className="investigate"><strong>Investigation prompt</strong><p>{index===5?store.note:'Review the expense ratios and volume changes for this month. The September board prompts should not be assumed to describe this period.'}</p></div>
  <p className="footnote">Comparable sales: {exactMoney(row.sales)} versus {exactMoney(row.priorSales)} in the same month of 2025 ({signedPercent(current.growth)}). All stores are mature and included in the comparable base.</p>
 </Modal>;
}
function App(){
 const detailTrigger=useRef();const boardTrigger=useRef();
 const openDetail=(id,month,trigger=document.activeElement)=>{detailTrigger.current=trigger;setDetail({id,month});};
 const [region,setRegion]=useState('All regions');const [storeId,setStoreId]=useState('All stores');const [month,setMonth]=useState('2026-09');
 const [target,setTarget]=useState(20);const [detail,setDetail]=useState(null);const [ledgerPeriod,setLedgerPeriod]=useState('month');const [query,setQuery]=useState('');const [sort,setSort]=useState('margin');const [briefing,setBriefing]=useState(null);
 const validTarget=typeof target==='number'&&target>=0&&target<=100;const threshold=validTarget?target/100:null;
 const scope=useMemo(()=>selectRows(records,{region,storeId}),[region,storeId]);const currentRows=selectRows(scope,{month});const summary=summarize(currentRows);const monthIndex=months.indexOf(month);const previous=monthIndex?summarize(selectRows(scope,{month:months[monthIndex-1]})):null;
 const series=months.map(m=>summarize(selectRows(scope,{month:m})));
 const regionRows=['Coast','Piedmont','Highlands'].map(name=>({name,...summarize(selectRows(currentRows,{region:name}))})).filter(r=>r.sales);
 const ledgerRows=useMemo(()=>selectRows(scope,{month:ledgerPeriod==='all'?'All months':month}).filter(row=>`${row.store} ${row.region}`.toLowerCase().includes(query.toLowerCase())),[scope,month,ledgerPeriod,query]);const ledgerSummary=summarize(ledgerRows);
 const d=duke();const below=threshold===null?null:currentRows.filter(row=>status(row,threshold)==='Below target').length;
 const option={grid:{left:47,right:20,top:30,bottom:32},xAxis:{type:'category',data:monthLabels,axisTick:{show:false}},yAxis:{type:'value',min:0,max:validTarget?Math.max(40,Math.ceil(target/10)*10):40,axisLabel:{formatter:'{value}%'},splitLine:{lineStyle:{color:d.panel}}},series:[{name:'Contribution margin, %',type:'line',data:series.map(r=>+(r.margin*100).toFixed(3)),symbolSize:9,lineStyle:{width:3},itemStyle:{color:d.navy},markLine:validTarget?{silent:true,symbol:'none',label:{formatter:`Target ${target}%`,position:'insideEndTop'},lineStyle:{color:d.copper,type:'dashed'},data:[{yAxis:target}]}:undefined}]};
 const regionalOption={grid:{left:88,right:40,top:22,bottom:30},xAxis:{type:'value',max:validTarget?Math.max(40,Math.ceil(target/10)*10):40,axisLabel:{formatter:'{value}%'},splitLine:{lineStyle:{color:d.panel}}},yAxis:{type:'category',inverse:true,data:regionRows.map(r=>r.name),axisLine:{show:false},axisTick:{show:false}},series:[{name:'Contribution margin, %',type:'bar',barWidth:30,data:regionRows.map(r=>({value:+(r.margin*100).toFixed(3),itemStyle:{color:d.navy}})),label:{show:true,position:'right',formatter:item=>`${item.value.toFixed(1)}%`},markLine:validTarget?{silent:true,symbol:'none',label:{show:false},lineStyle:{color:d.copper,type:'dashed'},data:[{xAxis:target}]}:undefined}]};
 const reset=()=>{setRegion('All regions');setStoreId('All stores');setMonth('2026-09');setTarget(20);setQuery('');setLedgerPeriod('month');setSort('margin');};
 const agenda=[{id:'S01',label:'01 · Labor productivity',title:'Harbor Wharf',body:'Is the schedule following demand?',detail:'September sales rose 2.0% from August; labor hours rose 17.6%. Inspect coverage and overtime before changing staffing.'},{id:'S02',label:'02 · Purchasing & waste',title:'Market Square',body:'Where is product spend moving?',detail:'Product costs reached 39.0% of sales in September, up 3.6 percentage points from August. Check invoices, mix and waste.'},{id:'S05',label:'03 · Useful comparison',title:'Magnolia Lane',body:'What should we learn from a peer?',detail:'September margin reached 33.9%. Compare operating practices, but do not assume the store format and demand are equivalent.'}];
 return <><a className="skip" href="#main">Skip to operating review</a><header className="masthead"><a href="#main" className="brand"><span className="brand-symbol" aria-hidden="true">S</span><span>STILLWATER<span className="brand-small">COFFEE COMPANY</span></span></a><div className="masthead-meta"><span className="synthetic">CLASSROOM EXAMPLE</span><span>Operating review · 2026</span></div></header>
 <main id="main"><section className="page-heading"><div><p className="eyebrow">THE MONTHLY OPERATING REVIEW</p><h1>Growth needs a<br className="desktop-break"/> stronger bottom line.</h1><p className="intro">Twelve stores. Three regions. One clear view of where contribution holds—and where to investigate.</p></div><aside className="board-invite"><span className="small-label">SEPTEMBER BOARD AGENDA</span><h2>Start with the questions.</h2><p>Labor at Harbor Wharf. Product spend at Market Square. A peer worth understanding.</p><Button ref={boardTrigger} onClick={()=>setBriefing(0)}>Open board briefing</Button></aside></section>
 <section className="filters" aria-label="Dashboard filters"><NativeSelect label="Reporting month" value={month} onChange={e=>setMonth(e.target.value)} data={months.map((m,i)=>({value:m,label:`${monthLabels[i]} 2026`}))}/><NativeSelect label="Region" value={region} onChange={e=>{setRegion(e.target.value);setStoreId('All stores');}} data={['All regions','Coast','Piedmont','Highlands']}/><NativeSelect label="Store" value={storeId} onChange={e=>setStoreId(e.target.value)} data={[{value:'All stores',label:'All stores'},...stores.filter(s=>region==='All regions'||s.region===region).map(s=>({value:s.id,label:s.name}))]}/><NumberInput hideControls label="Margin target, %" description="Classroom assumption" value={target} onChange={setTarget} min={0} max={100} clampBehavior="none" decimalScale={1} error={!validTarget?'Enter 0–100':undefined}/><Button variant="outline" onClick={reset}>Reset view</Button></section>
 <div className="scope-line" aria-live="polite"><strong>{monthLabels[monthIndex]} 2026 · {storeId==='All stores'?region:stores.find(s=>s.id===storeId).name}</strong><span>{currentRows.length} mature stores · USD · synthetic data</span></div>
 <section className="kpis" aria-label="Operating indicators"><Kpi label="Net sales" value={money(summary.sales)} note={`${signedPercent(summary.growth)} vs same month last year`}/><Kpi label="Store contribution" value={money(summary.contribution)} note={previous?`${summary.contribution-previous.contribution>=0?'+':''}${money(summary.contribution-previous.contribution)} vs ${monthLabels[monthIndex-1]}`:'First month in sample'}/><Kpi label="Contribution margin" value={percent(summary.margin)} note={previous?`${points(summary.margin-previous.margin)} vs ${monthLabels[monthIndex-1]}`:'Sales less store operating costs'}/><Kpi label="Stores below target" value={below===null?'—':`${below} / ${currentRows.length}`} note={validTarget?`Below assumed ${target}% margin`:'Set a valid target to compare'} accent/></section>
 <section className="charts-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">THE SIX-MONTH VIEW</p><h2>Contribution has a trajectory.</h2></div><span className="unit-label">MARGIN, %</span></div><Chart option={option} label="Monthly contribution margins, with an optional classroom target. Exact data is in the expandable table below."/><details><summary>Read monthly chart data</summary><div className="native-scroll"><table><caption>Current region/store scope · April–September 2026</caption><thead><tr><th>Month</th><th>Sales</th><th>Contribution</th><th>Margin</th></tr></thead><tbody>{series.map((r,i)=><tr key={i}><th>{monthLabels[i]}</th><td>{exactMoney(r.sales)}</td><td>{exactMoney(r.contribution)}</td><td>{percent(r.margin)}</td></tr>)}</tbody></table></div></details></article>
 <article className="panel"><div className="panel-heading"><div><p className="eyebrow">REGIONAL PERSPECTIVE</p><h2>Compare the mix.</h2></div></div><Chart option={regionalOption} onClick={event=>{setRegion(event.name);setStoreId('All stores');}} label="Regional contribution margin. Use region buttons below for a keyboard equivalent."/><div className="region-controls">{regionRows.map(r=><button key={r.name} onClick={()=>{setRegion(r.name);setStoreId('All stores');}}>{r.name}<strong>{percent(r.margin)}</strong></button>)}</div><p className="footnote">Sales-weighted margins. Dashed line is the assumed target. Select a region to focus the review.</p></article></section>
 <section className="investigations"><div className="section-title"><div><p className="eyebrow">SEPTEMBER · COMPANY-WIDE WATCHLIST</p><h2>Three conversations worth having.</h2></div><p>These prompts stay fixed to September, regardless of the dashboard filters.</p></div><div className="agenda-grid">{agenda.map(item=><article key={item.id}><p className="small-label">{item.label}</p><h3>{item.title}</h3><p>{item.body}</p><button onClick={()=>openDetail(item.id,'2026-09')}>Inspect store</button></article>)}</div></section>
 <section className="panel ledger-section"><div className="section-title"><div><p className="eyebrow">THE OPERATING LEDGER</p><h2>Put the numbers on the table.</h2></div><SegmentedControl aria-label="Ledger period" value={ledgerPeriod} onChange={setLedgerPeriod} data={[{label:'Selected month',value:'month'},{label:'Full six months',value:'all'}]}/></div><div className="ledger-filters"><TextInput label="Search the ledger" placeholder="Store or region" value={query} onChange={e=>setQuery(e.target.value)}/><NativeSelect label="Sort ascending" value={sort} onChange={e=>setSort(e.target.value)} data={[{value:'margin',label:'Contribution margin'},{value:'sales',label:'Sales'},{value:'store',label:'Store name'},{value:'month',label:'Month'}]}/><Button variant="outline" disabled={storeId==='All stores'} onClick={()=>openDetail(storeId,month)}>Inspect selected store</Button></div><p className="ledger-total" aria-live="polite">{ledgerRows.length} records · Sales {exactMoney(ledgerSummary.sales)} · Contribution {exactMoney(ledgerSummary.contribution)} · Weighted margin {percent(ledgerSummary.margin)}</p><Ledger rows={ledgerRows} sort={sort} onInspect={openDetail}/><p className="footnote">Sort column headers or use the control above. Scroll the ledger horizontally for cost lines, transactions and labor productivity. Store names open the month’s detail.</p><details><summary>Use accessible ledger table</summary><div className="native-scroll"><table><caption>The same filtered records, with exact USD; sorted by the selected control.</caption><thead><tr>{['Store / month','Region','Sales','Contribution','Margin','Sales YoY','Product','Labor','Occupancy / other','Transactions','Labor hours'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{ledgerRows.map(r=>({...r,...summarize([r])})).sort((a,b)=>typeof a[sort]==='string'?a[sort].localeCompare(b[sort]):a[sort]-b[sort]).map(row=><tr key={row.id}><th><button onClick={()=>openDetail(row.storeId,row.month)}>{row.store} / {row.month}</button></th><td>{row.region}</td><td>{exactMoney(row.sales)}</td><td>{exactMoney(row.contribution)}</td><td>{percent(row.margin)}</td><td>{signedPercent(row.growth)}</td><td>{exactMoney(row.product)}</td><td>{exactMoney(row.labor)}</td><td>{exactMoney(row.other)}</td><td>{row.transactions}</td><td>{row.hours}</td></tr>)}</tbody></table>{!ledgerRows.length&&<p>No records match these filters.</p>}</div></details></section>
 <section className="method"><h2>Know what this view can tell you.</h2><div><p><strong>Store contribution</strong> = net sales − product cost − store labor − occupancy and other store operating costs. Headquarters, taxes and financing are excluded. This is not company profit. Product cost includes waste; it is not subtracted twice.</p><p><strong>Comparable sales</strong> compares the selected 2026 month with the same month of 2025. All 12 fictional stores are mature. Group rates are calculated from totals, never averaged across stores. The target is a classroom assumption, not an industry benchmark.</p><p><strong>Read changes as prompts.</strong> These monthly records cannot separate price, mix, waste, service quality or demand. Sales per labor hour measures revenue productivity, not staffing adequacy. No data is uploaded or retained; filters reset on refresh.</p></div></section>
 </main><footer><span>Stillwater Coffee is fictional. Synthetic classroom data; no institutional affiliation or endorsement.</span><div><a href="https://github.com/jordanmeyer/bab-example-executive">Source code</a><a href={`${import.meta.env.BASE_URL}THIRD-PARTY-NOTICES.txt`}>Third-party notices</a></div></footer>
 <Detail detail={detail} onClose={()=>setDetail(null)} onReturnFocus={()=>detailTrigger.current?.focus()}/>
 <Modal opened={briefing!==null} onClose={()=>setBriefing(null)} returnFocus={!detail} closeButtonProps={{'aria-label':'Close board briefing'}} title="September board briefing" size="lg" centered>{briefing!==null&&<div className="briefing"><p className="eyebrow">QUESTION {briefing+1} OF 3 · SYNTHETIC CLASSROOM DISCUSSION</p><h2>{agenda[briefing].body}</h2><p className="briefing-store">{agenda[briefing].title}</p><p>{agenda[briefing].detail}</p><div className="investigate"><strong>Decision for discussion</strong><p>{['Request a daypart and overtime review, with a service-quality check. The ledger alone does not justify reducing staffing.','Request a purchase-price, recipe-mix and waste reconciliation. Separate changes in input prices from avoidable loss.','Compare practices with similar formats, then define a small trial. Do not extrapolate a single store’s results to expansion.'][briefing]}</p></div><div className="brief-actions"><Button variant="outline" onClick={()=>{openDetail(agenda[briefing].id,'2026-09',boardTrigger.current);setBriefing(null);}}>Inspect the evidence</Button><Button disabled={briefing===0} variant="outline" onClick={()=>setBriefing(briefing-1)}>Previous</Button>{briefing<2?<Button onClick={()=>setBriefing(briefing+1)}>Next question</Button>:<Button onClick={()=>setBriefing(null)}>Finish briefing</Button>}</div></div>}</Modal></>;
}
function Kpi({label,value,note,accent}){return <article className={accent?'kpi accent':'kpi'}><p>{label}</p><strong>{value}</strong><span>{note}</span></article>;}
createRoot(document.getElementById('root')).render(<MantineProvider theme={mantineTheme()} forceColorScheme="light"><App/></MantineProvider>);
