import seedrandom from 'seedrandom';
import { defaults, demandSequence, simulate, summarize, run, validate, toCSV } from '../app/model.js';
let failed = 0, passed = 0;
function test(name, callback) { const item = document.createElement('li'); try { const detail = callback(); passed++; item.textContent = `PASS — ${name}${detail ? ': ' + detail : ''}`; } catch (error) { failed++; item.className = 'fail'; item.textContent = `FAIL — ${name}: ${error.message}`; } document.querySelector('#results').append(item); }
function equal(actual, expected) { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw Error(`expected ${JSON.stringify(expected)}, observed ${JSON.stringify(actual)}`); }
function ok(value) { if (!value) throw Error('condition failed'); }
test('Published seedrandom reference draws, without changing global RNG', () => { const original = Math.random; const r = seedrandom('hello.'); equal([r(), r()], [0.9282578795792454, 0.3752569768646784]); ok(Math.random === original); equal(demandSequence('hello.', 2, 0, 12), [12, 4]); });
test('Independent one-day known answers', () => { const a = simulate([3], {...defaults,start:10}, 'daily')[0]; const b = simulate([12], {...defaults,start:10}, 'daily')[0]; equal([a.stock,a.unmet,b.stock,b.unmet],[7,0,0,2]); });
test('Four-day stock/shortage and trigger sequence', () => { const rows = simulate([3,3,3,3], {...defaults,start:10,point:0,quantity:5,lead:2}, 'daily'); equal(rows.map(r=>r.stock),[7,4,1,0]);equal(rows.map(r=>r.unmet),[0,0,0,2]);equal(rows.map(r=>r.ordered),[0,0,0,5]); });
test('Day d+L receipt and outstanding orders suppress duplicate orders', () => { const rows = simulate([0,0,0], {...defaults,start:0,point:0,quantity:5,lead:2}, 'daily'); equal(rows.map(r=>[r.arrivals,r.stock,r.ordered,r.pending]),[[0,0,5,5],[0,0,0,5],[5,5,0,0]]); });
test('Weekly end-day7 review and start-day9 receipt', () => { const rows = simulate(Array(9).fill(0), {...defaults,start:0,target:10,lead:2}, 'weekly');equal(rows.map(r=>r.ordered),[0,0,0,0,0,0,10,0,0]);equal(rows.map(r=>r.arrivals),[0,0,0,0,0,0,0,0,10]); });
test('Arrivals precede demand; positive lead1', () => { const rows = simulate([0,6], {...defaults,start:0,point:0,quantity:5,lead:1}, 'daily'); equal([rows[1].arrivals,rows[1].fulfilled,rows[1].unmet],[5,5,1]); });
test('Fixed-demand and zero-demand limits', () => { equal(demandSequence('x',4,3,3),[3,3,3,3]);const stats = summarize(simulate([0,0], {...defaults,start:10},'weekly'));equal([stats.fill,stats.demand,stats.meanStock],[100,0,10]); });
test('Seed repeat/change and identical demand across policies', () => { equal(run(defaults),run(defaults));ok(JSON.stringify(run({...defaults,seed:'different'}).daily)!==JSON.stringify(run(defaults).daily));const r=run(defaults);equal(r.daily.map(x=>x.demand),r.weekly.map(x=>x.demand)); });
test('Uniform0..12 independent mean/variance-derived tolerances (100000 draws)', () => { const sample=demandSequence('distribution-check-v1',100000,0,12);const mean=sample.reduce((a,b)=>a+b,0)/sample.length;const counts=Array(13).fill(0);sample.forEach(x=>counts[x]++);ok(Math.abs(mean-6)<.06);ok(counts.every(n=>Math.abs(n-100000/13)<500));return `mean ${mean}; bin range ${Math.min(...counts)}–${Math.max(...counts)}`; });
test('Per-day material and demand conservation for large realistic case', () => { const r=run({...defaults,days:90,start:10000,min:500,max:1000,lead:30,point:10000,quantity:10000,target:10000});for(const rows of Object.values(r)){let ordered=0,arrived=0;for(const row of rows){equal(row.opening+row.arrivals-row.fulfilled,row.stock);equal(row.fulfilled+row.unmet,row.demand);ok(row.stock>=0);ordered+=row.ordered;arrived+=row.arrivals;equal(ordered-arrived,row.pending);}} });
test('Reject blank/noninteger/negative/inverted and impractical inputs', () => {for(const change of [{seed:''},{days:0},{days:91},{lead:0},{lead:1.5},{min:-1},{min:13,max:12},{start:NaN},{quantity:0}]){let rejected=false;try{validate({...defaults,...change});}catch{rejected=true;}ok(rejected);} });
test('Coordinator-derived four-day policy comparison', () => { const input={...defaults,days:4,min:3,max:3,start:10,point:4,quantity:5,lead:2};const r=run(input);equal(r.daily.map(x=>x.stock),[7,4,1,3]);equal(r.daily.map(x=>x.ordered),[0,5,0,5]);equal(r.weekly.map(x=>x.stock),[7,4,1,0]);equal(r.weekly.map(x=>x.unmet),[0,0,0,2]);equal(summarize(r.daily).meanStock,3.75);equal(summarize(r.daily).fill,100);equal(summarize(r.weekly).fill,100*10/12); });
test('CSV two-policy rows, input metadata and escaped seed', () => {const input={...defaults,days:2,seed:'a,"b'};const csv=toCSV(run(input),input);equal(csv.split('\r\n').length,5);ok(csv.includes('"a,""b"'));ok(csv.includes('input_seed'));ok(csv.includes('"weekly"'));});
document.querySelector('#status').textContent = `${passed} passed; ${failed} failed. Complete.`;
