import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MantineProvider,Button,NativeSelect,NumberInput,TextInput,Modal,SegmentedControl} from '@mantine/core';
import * as echarts from 'echarts/core';
import {LineChart,BarChart} from 'echarts/charts';
import {GridComponent,TooltipComponent,MarkLineComponent,AriaComponent} from 'echarts/components';
import {SVGRenderer} from 'echarts/renderers';
echarts.use([LineChart,BarChart,GridComponent,TooltipComponent,MarkLineComponent,AriaComponent,SVGRenderer]);
import '@mantine/core/styles.css';
import './theme/duke-tokens.css';
import './theme/duke-fonts.css';
import './theme/base.css';
import './theme/mantine.css';
import './style.css';
import {mantineTheme} from './theme/mantine.js';
import {echartsTheme} from './theme/echarts.js';
import {duke} from './theme/tokens.js';
import {records,stores,months,monthLabels} from './data.js';
import {summarize,selectRows,status,costBridge,money,exactMoney,percent,signedPercent,points} from './model.js';

function Chart({option,label,onClick}) {
 const host=useRef();
 useEffect(()=>{
  const chart=echarts.init(host.current,echartsTheme(),{renderer:'svg'});
  chart.setOption({...option,animation:false,aria:{enabled:true,label:{description:label}},tooltip:{trigger:'axis',renderMode:'richText'}});
  if(onClick) chart.on('click',onClick);
  const resize=new ResizeObserver(()=>chart.resize());resize.observe(host.current);
  return ()=>{resize.disconnect();chart.dispose();};
 },[option]);
 return <div ref={host} className="chart" role="img" aria-label={label}/>;
}

const columnLabels={sales:'Sales',product:'Product cost',labor:'Store labor',other:'Occupancy / other'};
function Ledger({rows,onInspect,allMonths}) {
 const [sort,setSort]=useState({key:'margin',direction:1});
 const columns=[['store','Store'],...(allMonths?[['month','Month']]:[]),['region','Region'],['sales','Sales, USD'],['contribution','Contribution, USD'],['margin','Margin'],['growth','Sales YoY'],['hours','Labor hours']];
 const sorted=rows.map(row=>({...row,...summarize([row])})).sort((a,b)=>sort.direction*(typeof a[sort.key]==='string'?a[sort.key].localeCompare(b[sort.key]):a[sort.key]-b[sort.key]));
 return <div className="native-scroll" tabIndex="0" aria-label="Operating ledger, scroll horizontally for more columns"><table><caption>Current filters · select a store for cost lines and productivity. USD rounded to dollars.</caption><thead><tr>{columns.map(([key,label])=><th key={key} scope="col" aria-sort={sort.key===key?(sort.direction===1?'ascending':'descending'):'none'}><button onClick={()=>setSort({key,direction:sort.key===key?-sort.direction:1})}>{label}{sort.key===key?(sort.direction===1?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{sorted.map(row=><tr key={row.id}>{columns.map(([key])=>key==='store'?<th scope="row" key={key}><button onClick={()=>onInspect(row.storeId,row.month)}>{row.store}</button></th>:<td className={['month','region'].includes(key)?'text':''} key={key}>{key==='month'?`${monthLabels[months.indexOf(row.month)]} 2026`:['sales','contribution'].includes(key)?money(row[key]):key==='margin'?percent(row[key]):key==='growth'?signedPercent(row[key]):key==='hours'?row[key].toLocaleString():row[key]}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records match these filters.</p>}</div>;
}
function BoardEvidence({index}) {
 const id=['S01','S02','S05'][index];const rows=selectRows(records,{storeId:id});const aug=rows[4],sep=rows[5];const d=duke();
 let option,comparison,caption;
 if(index===0){
  caption='April = 100 for both series. Indexed lines compare growth, not dollar and hour levels.';
  option={xAxis:{type:'category',data:monthLabels},yAxis:{type:'value',min:90,max:150,axisLabel:{formatter:'{value}'}},series:[{name:'Sales (Apr = 100)',type:'line',data:rows.map(r=>r.sales/rows[0].sales*100),lineStyle:{width:3},itemStyle:{color:d.navy}},{name:'Labor hours (Apr = 100)',type:'line',data:rows.map(r=>r.hours/rows[0].hours*100),lineStyle:{width:3,type:'dashed'},itemStyle:{color:d.copper}}]};
  comparison=[['Sales',money(aug.sales),money(sep.sales)],['Labor hours',aug.hours.toLocaleString(),sep.hours.toLocaleString()],['Sales / labor hour',exactMoney(aug.sales/aug.hours),exactMoney(sep.sales/sep.hours)],['Contribution',money(summarize([aug]).contribution),money(summarize([sep]).contribution)]];
 }else if(index===1){
  caption='Solid navy: product cost as a share of sales. Dashed copper: contribution margin. Percentage axis starts at zero.';
  option={xAxis:{type:'category',data:monthLabels},yAxis:{type:'value',min:0,max:40,axisLabel:{formatter:'{value}%'}},series:[{name:'Product cost, % of sales',type:'line',data:rows.map(r=>r.product/r.sales*100),lineStyle:{width:3},itemStyle:{color:d.navy}},{name:'Contribution margin, %',type:'line',data:rows.map(r=>summarize([r]).margin*100),lineStyle:{width:3,type:'dashed'},itemStyle:{color:d.copper}}]};
  comparison=[['Product cost',money(aug.product),money(sep.product)],['Product / sales',percent(aug.product/aug.sales),percent(sep.product/sep.sales)],['Contribution',money(summarize([aug]).contribution),money(summarize([sep]).contribution)]];
 }else{
  caption='September margin: Magnolia Lane versus the other Piedmont stores. Bars start at zero; different formats may explain differences.';
  const peers=selectRows(records,{region:'Piedmont',month:'2026-09'});const others=summarize(peers.filter(r=>r.storeId!==id));
  option={xAxis:{type:'value',max:40,axisLabel:{formatter:'{value}%'}},yAxis:{type:'category',inverse:true,data:peers.map(r=>r.store)},series:[{name:'Contribution margin, %',type:'bar',data:peers.map(r=>summarize([r]).margin*100),label:{show:true,position:'right',formatter:p=>`${p.value.toFixed(1)}%`}}]};
  comparison=[['Contribution margin',percent(others.margin),percent(summarize([sep]).margin)],['Sales / labor hour',exactMoney(others.salesPerHour),exactMoney(sep.sales/sep.hours)],['Labor / sales',percent(others.labor/others.sales),percent(sep.labor/sep.sales)]];
 }
 return <><Chart option={{...option,grid:{left:index===2?112:44,right:42,top:15,bottom:30}}} label={caption}/><p className="footnote">{caption}{index===0?' Solid navy: sales. Dashed copper: hours.':''}</p><div className="native-scroll"><table><caption>Evidence for this decision · {index===2?'September 2026':'August–September 2026'}</caption><thead><tr><th>Measure</th><th>{index===2?'Other Piedmont stores':'August'}</th><th>{index===2?'Magnolia Lane':'September'}</th></tr></thead><tbody>{comparison.map(row=><tr key={row[0]}><th scope="row">{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div></>;
}
function Detail({detail,onClose,onReturnFocus}) {
 if(!detail)return <Modal opened={false} onClose={onClose} returnFocus={false} onExitTransitionEnd={onReturnFocus} closeButtonProps={{'aria-label':'Close store details'}}/>;
 const row=records.find(row=>row.storeId===detail.id&&row.month===detail.month);
 const store=stores.find(store=>store.id===detail.id);const index=months.indexOf(detail.month);
 const previous=index?records.find(r=>r.storeId===detail.id&&r.month===months[index-1]):null;
 const current=summarize([row]);const prior=previous?summarize([previous]):null;
 return <Modal opened onClose={onClose} returnFocus={false} onExitTransitionEnd={onReturnFocus} closeButtonProps={{'aria-label':'Close store details'}} title={`${store.name} · ${monthLabels[index]} 2026`} size="xl" centered>
  <p className="eyebrow">STORE {store.id} · {store.region.toUpperCase()} · SYNTHETIC DATA</p>
  <div className="detail-metrics"><div><span>Store contribution</span><strong>{money(current.contribution)}</strong></div><div><span>Contribution margin</span><strong>{percent(current.margin)}</strong></div><div><span>Sales per labor hour</span><strong>{exactMoney(current.salesPerHour)}</strong></div></div>
  <h3>Follow the change in the ledger</h3>
  {previous?<><p>Compared with {monthLabels[index-1]}: contribution {current.contribution>=prior.contribution?'rose':'fell'} by {money(Math.abs(current.contribution-prior.contribution))}; margin moved {points(current.margin-prior.margin)}. Rates use each month's own sales.</p>
  <div className="native-scroll"><table><caption>Cost bridge · whole USD and percentage-point changes</caption><thead><tr><th>Line</th><th>{monthLabels[index-1]}</th><th>{monthLabels[index]}</th><th>Change, USD</th><th>Share of sales change</th></tr></thead><tbody>{costBridge(row,previous).map(item=><tr key={item.key}><th>{columnLabels[item.key]}</th><td>{money(item.previous)}</td><td>{money(item.current)}</td><td>{item.change>=0?'+':''}{money(item.change)}</td><td>{item.key==='sales'?'—':points(item.ratioChange)}</td></tr>)}<tr className="total"><th>Contribution</th><td>{money(prior.contribution)}</td><td>{money(current.contribution)}</td><td>{money(current.contribution-prior.contribution)}</td><td>{points(current.margin-prior.margin)}</td></tr></tbody></table></div>
  <p className="detail-note">Labor hours: {previous.hours.toLocaleString()} to {row.hours.toLocaleString()}. Transactions: {previous.transactions.toLocaleString()} to {row.transactions.toLocaleString()}. Sales per labor hour: {exactMoney(prior.salesPerHour)} to {exactMoney(current.salesPerHour)}.</p></>:<p>April is the first month in the sample; no preceding month is available. April sales are {money(row.sales)}, product cost {money(row.product)}, labor {money(row.labor)}, occupancy/other {money(row.other)}.</p>}
  <div className="investigate"><strong>Investigation prompt</strong><p>{index===5?store.note:'Review the expense ratios and volume changes for this month. The September board prompts should not be assumed to describe this period.'}</p></div>
  <p className="footnote">Comparable sales: {money(row.sales)} versus {money(row.priorSales)} in the same month of 2025 ({signedPercent(current.growth)}). All stores are mature and included in the comparable base.</p>
 </Modal>;
}
function App(){
 const detailTrigger=useRef();const boardTrigger=useRef();
 const openDetail=(id,month,trigger=document.activeElement)=>{detailTrigger.current=trigger;setDetail({id,month});};
 const [region,setRegion]=useState('All regions');const [storeId,setStoreId]=useState('All stores');const [month,setMonth]=useState('2026-09');
 const [target,setTarget]=useState(20);const [detail,setDetail]=useState(null);const [ledgerPeriod,setLedgerPeriod]=useState('month');const [query,setQuery]=useState('');const [briefing,setBriefing]=useState(null);const [view,setView]=useState('overview');
 const validTarget=typeof target==='number'&&target>=0&&target<=100;const threshold=validTarget?target/100:null;
 const scope=useMemo(()=>selectRows(records,{region,storeId}),[region,storeId]);const currentRows=selectRows(scope,{month});const summary=summarize(currentRows);const monthIndex=months.indexOf(month);const previous=monthIndex?summarize(selectRows(scope,{month:months[monthIndex-1]})):null;
 const series=months.map(m=>summarize(selectRows(scope,{month:m})));
 const regionRows=['Coast','Piedmont','Highlands'].map(name=>({name,...summarize(selectRows(records,{month,region:name}))})).filter(r=>r.sales);
 const ledgerRows=useMemo(()=>selectRows(scope,{month:ledgerPeriod==='all'?'All months':month}).filter(row=>`${row.store} ${row.region}`.toLowerCase().includes(query.toLowerCase())),[scope,month,ledgerPeriod,query]);const ledgerSummary=summarize(ledgerRows);
 const d=duke();const below=threshold===null?null:currentRows.filter(row=>status(row,threshold)==='Below target').length;
 const option={grid:{left:47,right:20,top:30,bottom:32},xAxis:{type:'category',data:monthLabels,axisTick:{show:false}},yAxis:{type:'value',min:Math.floor(Math.min(...series.map(r=>r.margin*100),...(validTarget?[target]:[])))-1,max:Math.ceil(Math.max(...series.map(r=>r.margin*100),...(validTarget?[target]:[])))+1,axisLabel:{formatter:'{value}%'},splitLine:{lineStyle:{color:d.panel}}},series:[{name:'Contribution margin, %',type:'line',data:series.map(r=>+(r.margin*100).toFixed(3)),symbolSize:9,lineStyle:{width:3},itemStyle:{color:d.navy},markLine:validTarget?{silent:true,symbol:'none',label:{show:false},lineStyle:{color:d.copper,type:'dashed'},data:[{yAxis:target}]}:undefined}]};
 const regionalOption={grid:{left:88,right:40,top:22,bottom:30},xAxis:{type:'value',max:validTarget?Math.max(40,Math.ceil(target/10)*10):40,axisLabel:{formatter:'{value}%'},splitLine:{lineStyle:{color:d.panel}}},yAxis:{type:'category',inverse:true,data:regionRows.map(r=>r.name),axisLine:{show:false},axisTick:{show:false}},series:[{name:'Contribution margin, %',type:'bar',barWidth:30,data:regionRows.map(r=>({value:+(r.margin*100).toFixed(3),itemStyle:{color:d.navy}})),label:{show:true,position:'right',formatter:item=>`${item.value.toFixed(1)}%`},markLine:validTarget?{silent:true,symbol:'none',label:{show:false},lineStyle:{color:d.copper,type:'dashed'},data:[{xAxis:target}]}:undefined}]};
 const reset=()=>{setRegion('All regions');setStoreId('All stores');setMonth('2026-09');setTarget(20);setQuery('');setLedgerPeriod('month');setView('overview');};
 const agenda=[{id:'S01',label:'01 · Labor productivity',title:'Harbor Wharf',body:'Is the schedule following demand?',detail:'September sales rose 2.0% from August; labor hours rose 17.6%. Inspect coverage and overtime before changing staffing.'},{id:'S02',label:'02 · Purchasing & waste',title:'Market Square',body:'Where is product spend moving?',detail:'Product costs reached 39.0% of sales in September, up 3.6 percentage points from August. Check invoices, mix and waste.'},{id:'S05',label:'03 · Useful comparison',title:'Magnolia Lane',body:'What should we learn from a peer?',detail:'September margin reached 33.9%. Compare operating practices, but do not assume the store format and demand are equivalent.'}];
 return <><a className="skip" href="#main">Skip to operating review</a><header className="masthead"><a href="#main" className="brand"><span className="brand-symbol" aria-hidden="true">S</span><span>STILLWATER<span className="brand-small">COFFEE COMPANY</span></span></a><div className="masthead-meta"><span className="synthetic">CLASSROOM EXAMPLE</span><span>Executive operating dashboard</span></div></header>
 <main id="main"><section className="page-heading"><div><p className="eyebrow">THE MONTHLY OPERATING REVIEW</p><h1>Growth needs a stronger bottom line.</h1><p className="intro">Learn to separate sales growth from contribution, then use cost and productivity evidence to choose an investigation.</p></div><aside className="board-invite"><span className="small-label">SEPTEMBER BOARD AGENDA</span><h2>Start with the questions.</h2><p>Labor at Harbor Wharf. Product spend at Market Square. A peer worth understanding.</p><Button ref={boardTrigger} onClick={()=>setBriefing(0)}>Open board briefing</Button></aside></section>
 <section className="filters" aria-label="Dashboard filters"><NativeSelect label="Reporting month" value={month} onChange={e=>setMonth(e.target.value)} data={months.map((m,i)=>({value:m,label:`${monthLabels[i]} 2026`}))}/><NativeSelect label="Region" value={region} onChange={e=>{setRegion(e.target.value);setStoreId('All stores');}} data={['All regions','Coast','Piedmont','Highlands']}/><NativeSelect label="Store" value={storeId} onChange={e=>setStoreId(e.target.value)} data={[{value:'All stores',label:'All stores'},...stores.filter(s=>region==='All regions'||s.region===region).map(s=>({value:s.id,label:s.name}))]}/><NumberInput hideControls label="Margin target, %" description="Classroom assumption" value={target} onChange={setTarget} min={0} max={100} clampBehavior="none" decimalScale={1} error={!validTarget?'Enter 0–100':undefined}/><Button variant="outline" onClick={reset}>Reset view</Button></section>
 <div className="scope-line" aria-live="polite"><strong>{monthLabels[monthIndex]} 2026 · {storeId==='All stores'?region:stores.find(s=>s.id===storeId).name}</strong><span>{currentRows.length} mature {currentRows.length===1?'store':'stores'} · USD · synthetic classroom data</span></div>
 <section className="kpis" aria-label="Operating indicators"><Kpi label="Net sales" value={money(summary.sales)} note={`${signedPercent(summary.growth)} vs same month last year`}/><Kpi label="Store contribution" value={money(summary.contribution)} note={previous?`${summary.contribution-previous.contribution>=0?'+':''}${money(summary.contribution-previous.contribution)} vs ${monthLabels[monthIndex-1]}`:'First month in sample'}/><Kpi label="Contribution margin" value={percent(summary.margin)} note={summary.priorMargin===null?'Prior-year margin unavailable':`${points(summary.margin-summary.priorMargin)} vs same month last year`}/><Kpi label="Stores below target" value={below===null?'—':`${below} / ${currentRows.length}`} note={validTarget?`Below assumed ${target}% margin`:'Set a valid target to compare'} accent/></section>
 <div className="view-tabs"><Button variant={view==='overview'?'filled':'outline'} aria-pressed={view==='overview'} onClick={()=>setView('overview')}>Decision overview</Button><Button variant={view==='ledger'?'filled':'outline'} aria-pressed={view==='ledger'} onClick={()=>setView('ledger')}>Operating ledger</Button></div>{view==='overview'?<section className="charts-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">THE SIX-MONTH VIEW</p><h2>See the margin change.</h2></div><span className="unit-label">MARGIN, %</span></div><p className="chart-context">{points(series[5].margin-series[0].margin)} from April to September · line axis is zoomed{validTarget?` · dashed target ${target}%`: '.'}</p><Chart option={option} label="Monthly contribution margins, with an optional classroom target. Exact data is in the expandable table below."/><details><summary>Read monthly chart data</summary><div className="native-scroll"><table><caption>Current region/store scope · April–September 2026</caption><thead><tr><th>Month</th><th>Sales</th><th>Contribution</th><th>Margin</th><th>Prior-year margin</th></tr></thead><tbody>{series.map((r,i)=><tr key={i}><th>{monthLabels[i]}</th><td>{money(r.sales)}</td><td>{money(r.contribution)}</td><td>{percent(r.margin)}</td><td>{percent(r.priorMargin)}</td></tr>)}</tbody></table></div></details></article>
 <article className="panel"><div className="panel-heading"><div><p className="eyebrow">REGIONAL PERSPECTIVE</p><h2>Compare the mix.</h2></div></div><Chart option={regionalOption} label="Regional contribution margins for the reporting month. Exact values appear on each bar; the Region filter above controls the dashboard."/><p className="footnote">Company-wide regions for the selected month. Use the labeled Region filter above to focus the review. Dashed line: assumed target.</p></article></section>:
 <section className="panel ledger-section"><div className="section-title"><div><p className="eyebrow">THE OPERATING LEDGER</p><h2>Put the numbers on the table.</h2></div><SegmentedControl aria-label="Ledger period" value={ledgerPeriod} onChange={setLedgerPeriod} data={[{label:'Selected month',value:'month'},{label:'Full six months',value:'all'}]}/></div><div className="ledger-filters"><TextInput label="Search the ledger" placeholder="Store or region" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="ledger-total" aria-live="polite">{ledgerRows.length} {ledgerRows.length===1?'record':'records'} · Sales {money(ledgerSummary.sales)} · Contribution {money(ledgerSummary.contribution)} · Weighted margin {percent(ledgerSummary.margin)}</p><Ledger rows={ledgerRows} allMonths={ledgerPeriod==='all'} onInspect={openDetail}/><p className="footnote">Select a column heading to sort; select again to reverse. Store names open the month’s detail. All filters update immediately.</p></section>}
 <details className="method"><summary>How to read the measures and limitations</summary><h2>Know what this view can tell you.</h2><div><p><strong>Store contribution</strong> = net sales − product cost − store labor − occupancy and other store operating costs. Headquarters, taxes and financing are excluded. This is not company profit. Product cost includes waste; it is not subtracted twice.</p><p><strong>Comparable sales</strong> compares the selected 2026 month with the same month of 2025. All 12 fictional stores are mature. Group rates are calculated from totals, never averaged across stores. The target is a classroom assumption, not an industry benchmark.</p><p><strong>Read changes as prompts.</strong> These monthly records cannot separate price, mix, waste, service quality or demand. Sales per labor hour measures revenue productivity, not staffing adequacy. No data is uploaded or retained; filters reset on refresh.</p></div></details>
 </main><footer><span>Stillwater Coffee is fictional. Synthetic classroom data; no institutional affiliation or endorsement.</span><div><a href="https://github.com/jordanmeyer/bab-example-executive/blob/main/BUILD-STORY.md">How this was built</a><a href="https://github.com/jordanmeyer/bab-example-executive">Source code</a><a href={`${import.meta.env.BASE_URL}THIRD-PARTY-NOTICES.txt`}>Third-party notices</a></div></footer>
 <Detail detail={detail} onClose={()=>setDetail(null)} onReturnFocus={()=>detailTrigger.current?.focus()}/>
 <Modal opened={briefing!==null} onClose={()=>setBriefing(null)} returnFocus={!detail} closeButtonProps={{'aria-label':'Close board briefing'}} title="September board briefing" size="xl" centered>{briefing!==null&&<div className="briefing"><p className="eyebrow">QUESTION {briefing+1} OF 3 · SYNTHETIC CLASSROOM DISCUSSION</p><h2>{agenda[briefing].body}</h2><p className="briefing-store">{agenda[briefing].title}</p><p>{agenda[briefing].detail}</p><BoardEvidence index={briefing}/><div className="investigate"><strong>Decision for discussion</strong><p>{['Request a daypart and overtime review, with a service-quality check. The ledger alone does not justify reducing staffing.','Request a purchase-price, recipe-mix and waste reconciliation. Separate changes in input prices from avoidable loss.','Compare practices with similar formats, then define a small trial. Do not extrapolate a single store’s results to expansion.'][briefing]}</p></div><div className="brief-actions"><Button variant="outline" onClick={()=>{openDetail(agenda[briefing].id,'2026-09',boardTrigger.current);setBriefing(null);}}>Open full cost detail</Button><Button disabled={briefing===0} variant="outline" onClick={()=>setBriefing(briefing-1)}>Previous</Button>{briefing<2?<Button onClick={()=>setBriefing(briefing+1)}>Next question</Button>:<Button onClick={()=>setBriefing(null)}>Finish briefing</Button>}</div></div>}</Modal></>;
}
function Kpi({label,value,note,accent}){return <article className={accent?'kpi accent':'kpi'}><p>{label}</p><strong>{value}</strong><span>{note}</span></article>;}
const root=createRoot(document.getElementById('root'));
let visit=0;
const showFreshView=()=>root.render(<MantineProvider theme={mantineTheme()} forceColorScheme="light"><App key={visit++}/></MantineProvider>);
Promise.all([document.fonts.load("400 18px 'EB Garamond'"),document.fonts.load("400 14px 'Open Sans'"),document.fonts.load("600 14px 'Open Sans'")]).then(showFreshView);
// Native form restoration can run after React mounts. Replace both controls and results together.
window.addEventListener('pageshow',()=>requestAnimationFrame(showFreshView));
